# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'USBRelay_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from custom_comboBox import CustomComboBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 388)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setVerticalSpacing(24)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(30)
        self.gridLayout.setObjectName("gridLayout")
        self.times = QtWidgets.QLabel(self.centralwidget)
        self.times.setObjectName("times")
        self.gridLayout.addWidget(self.times, 3, 2, 1, 1)
        self.lineEdit_wait = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_wait.setObjectName("lineEdit_wait")
        self.gridLayout.addWidget(self.lineEdit_wait, 1, 1, 1, 1)
        self.seconds_on = QtWidgets.QLabel(self.centralwidget)
        self.seconds_on.setObjectName("seconds_on")
        self.gridLayout.addWidget(self.seconds_on, 1, 2, 1, 1)
        self.wait_time = QtWidgets.QLabel(self.centralwidget)
        self.wait_time.setObjectName("wait_time")
        self.gridLayout.addWidget(self.wait_time, 1, 0, 1, 1)
        self.loop_times = QtWidgets.QLabel(self.centralwidget)
        self.loop_times.setObjectName("loop_times")
        self.gridLayout.addWidget(self.loop_times, 3, 0, 1, 1)
        self.com_num = QtWidgets.QLabel(self.centralwidget)
        self.com_num.setObjectName("com_num")
        self.gridLayout.addWidget(self.com_num, 0, 0, 1, 1)
        self.lineEdit_loop = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_loop.setObjectName("lineEdit_loop")
        self.gridLayout.addWidget(self.lineEdit_loop, 3, 1, 1, 1)
        self.comboBox = CustomComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.second_off = QtWidgets.QLabel(self.centralwidget)
        self.second_off.setObjectName("second_off")
        self.gridLayout.addWidget(self.second_off, 4, 2, 1, 1)
        self.lineEdit_off_on = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_off_on.setObjectName("lineEdit_off_on")
        self.gridLayout.addWidget(self.lineEdit_off_on, 4, 1, 1, 1)
        self.sleep_off_to_on = QtWidgets.QLabel(self.centralwidget)
        self.sleep_off_to_on.setObjectName("sleep_off_to_on")
        self.gridLayout.addWidget(self.sleep_off_to_on, 4, 0, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 5, 1, 1, 1)
        self.current_times = QtWidgets.QLabel(self.centralwidget)
        self.current_times.setObjectName("current_times")
        self.gridLayout.addWidget(self.current_times, 5, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 5)
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setObjectName("start")
        self.gridLayout_2.addWidget(self.start, 1, 3, 1, 1)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setAutoRepeatDelay(300)
        self.stop_button.setAutoRepeatInterval(100)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout_2.addWidget(self.stop_button, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 440, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.times.setText(_translate("MainWindow", "次"))
        self.seconds_on.setText(_translate("MainWindow", "秒（s）"))
        self.wait_time.setText(_translate("MainWindow", "延时（ON->OFF）"))
        self.loop_times.setText(_translate("MainWindow", "重复次数"))
        self.com_num.setText(_translate("MainWindow", "COM串口号"))
        self.comboBox.setItemText(0, _translate("MainWindow", "请选择继电器串口号"))
        self.second_off.setText(_translate("MainWindow", "秒（s）"))
        self.sleep_off_to_on.setText(_translate("MainWindow", "延时（OFF->ON）"))
        self.current_times.setText(_translate("MainWindow", "当前执行次数"))
        self.start.setText(_translate("MainWindow", "开 始"))
        self.stop_button.setText(_translate("MainWindow", "停 止"))

